### ISSUE TITLE
to.have.prop doesn't work correctly with false value that is compared with undefined

### ISSUE THREAD

**Issue by nadiam84** [producthunt/chai-enzyme#147]
If a component has a prop set to `false` then `to.have.prop` check will pass when its value is compared with `undefined`. For example (all of them are green):

```
class ButtonComponent extends React.Component {
  static propTypes = {
    isDisabled: React.PropTypes.bool
  }
  static defaultProps = {
    isDisabled: false
  }
  render () {
    return (
      <div></div>
    )
  }
}

const wrapper = mount(<ButtonComponent />)

expect(wrapper).to.have.prop('isDisabled', false);
expect(wrapper).to.have.prop('isDisabled', undefined);
expect(wrapper).to.have.prop('isDisabled').equal(false);
```

**Comment by ljharb** [comment]
What's `ButtonComponent`? Elements have props, components don't.

**Comment by nadiam84** [comment]
Updated the example to make it more correct

**Comment by ljharb** [comment]
In this example, you're mounting what `ButtonComponent` *renders* - you don't need to assert on its props because you just passed them (and you don't need to assert on defaultProps, because that's an implementation detail of the component). In other words, the thing in the wrapper is the div and that's what you should be making assertions on.

**Comment by nigelrobbins3** [comment]
Saying the wrapper contains the div is not accurate in this case. If I further extend the example to render elements with props:
```jsx
class ButtonComponent extends React.Component {
  render() {
    return (
      <div id="foo">
        <span id="bar" />
      </div>
    );
  }
}

const wrapper = mount(<ButtonComponent baz="qux" />);
const spanWrapper = wrapper.find("span");

expect(spanWrapper).to.have.id("bar"); // passes
expect(spanWrapper).to.have.prop("id", "bar"); // passes

expect(wrapper).to.have.prop("baz", "qux"); // passes (even though it's on ButtonComponent)
expect(wrapper).to.have.id("foo"); // passes
expect(wrapper).to.have.prop("id", "foo"); // fails
```
So the `prop` assertion behaves differently on the root component in a way which is unexpected.

Why would I want to use `prop("id", "foo")` when I have `id("foo")`? I like to assert that my elements have a style prop, but I don't care what the values are (I find it very brittle to assert all the style properties and values). `expect(someWrapper).to.have.prop("style")`

There's some special casing that is done to the root wrapper, because the output from `wrapper.debug()` is:
```jsx
<ButtonComponent>
  <div id="foo">
    <span id="bar" />
  </div>
</ButtonComponent>
```
but `wrapper.children().debug()`:
```jsx
<span id="bar" />
```
Either enzyme does something special when it calls `children()`, or it does something special when it calls `debug()` on the root element. Regardless, the assert `expect(wrapper).to.have.prop("something")` is checking the `ButtonComponent` element, *not* the `div`. @ljharb is correct in that the wrapper is usually treated as containing the `div`, because I can use `id("foo")`. However, for the `prop` call, suddenly the element under test is the `ButtonComponent` again.

For all the reasons @ljharb brought up above, it seems that there is no need to have `prop` assert on the `ButtonComponent` itself, so this is a bug; the assertion should be using the `div`.

**Comment by ayrton** [comment]
@nadiam84 I believe this is fixed as of 0.7.0, can you confirm this please

**Comment by nigelrobbins3** [comment]
The original problem seems to have been fixed. The broken case now fails properly.
```js
expect(wrapper).to.have.prop('isDisabled', undefined);
```

Should I open a new issue for the problems I'm having accessing the root element for `to.have.prop`?

**Comment by ayrton** [comment]
@nigelrobbins3 yes please
@nadiam84 I'm closing this issue, feel free to re-open if you think this was a mistake
